name: video_analysis_env #mine is named differntly cuz im stupi ("imageAnalysis")
name: video_analysis_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.22.4
  - pandas=1.3.0
  - scikit-learn=1.2.2
  - matplotlib=3.7.5
  - seaborn=0.13.2
  - streamlit=1.35.0
  - opencv=4.0.1
  - ffmpeg=5.1.2
  - h5py=3.8.0
  - sqlite=3.45.3
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - tensorflow=2.13.0
  - tensorflow-estimator=2.13.0
  - tensorflow-io-gcs-filesystem=0.31.0
  - pip:
      - ffmpeg-python
      - clip
      - transnetv2
      - tqdm
      - requests



#to create environment:
#conda env create -f environment.yml
#conda activate video_analysis_env
