name: video_analysis_env #mine is named differntly cuz im stupi ("imageAnalysis")
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - opencv=4.0.1
  - tensorflow=2.3.0
  - numpy=1.18.5
  - pandas=1.2.5
  - scikit-learn=1.2.2
  - pytorch=2.3.0
  - sqlite=3.45.3
  - ffmpeg=5.1.2


#to create environment:
#conda env create -f environment.yml
#conda activate video_analysis_env
