name: video_analysis_env #mine is named differntly cuz im stupi ("imageAnalysis")
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - opencv=4.0.1
  - tensorflow=2.3.0
  - pytorch=2.3.0
  - torchvision
  - torchaudio
  - numpy=1.18.5
  - pandas=1.2.3
  - scikit-learn
  - ffmpeg=5.1.2
  - pip
  - sqlite=3.45.3


#to create environment:
#conda env create -f environment.yml
#conda activate video_analysis_env
